services:
  nextcloud:
    container_name: ${container_name}
    hostname: ${hostname}
    image: ${docker_image}:${docker_image_tag}
    restart: unless-stopped
    volumes:
      - './html:/var/www/html'
    networks:
      - web
    environment:
      MYSQL_HOST: ${db_host}
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.${service}.rule=Host(`${hostname}`)"
      - "traefik.http.routers.${service}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${service}.entrypoints=https"
      - "traefik.http.services.${service}.loadbalancer.server.port=80"
      - "traefik.http.routers.${service}.middlewares=${service}-allowlist,${service}-redirects,${service}-sts"
      - "traefik.http.middlewares.${service}-allowlist.ipallowlist.sourcerange=${ip_allowlist}"
      - "traefik.http.middlewares.${service}-redirects.redirectregex.permanent=true"
      - "traefik.http.middlewares.${service}-redirects.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.${service}-redirects.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.${service}-sts.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.${service}-sts.headers.STSPreload=true"
      - "traefik.http.middlewares.${service}-sts.headers.STSSeconds=15552000"

networks:
  web:
    external: true
